# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20171105_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='contenttypes.ContentType'),
        ),
    ]
