# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_auto_20171127_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
    ]
